# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, cgi, deepseq, exceptions, fastcgi, filepath, mtl }:

cabal.mkDerivation (self: {
  pname = "cgroups";
  version = "0.1";
  src = ./.;
  isLibrary = false;
  isExecutable = true;
  buildDepends = [ cgi deepseq exceptions fastcgi filepath mtl ];
  meta = {
    description = "A CGI/FastCGI module to manipulate cgroups on Linux";
    license = self.stdenv.lib.licenses.unfree;
    platforms = self.ghc.meta.platforms;
  };
})
